// Jest Snapshot v1, https://goo.gl/fbAQLP

exports[`should work 1`] = `
"
  (;;# define SEQ_ID_ADR 4;;)
  (;;# import set;;)(some wat)
(;;# import set_1;;)(some set1_wat)
(;;# define U 10;;)
(;;# $u = U;;)(local.set $u (i32.const 10))
(;;# U;;)(i32.const 10)(some wat2)
  (;;# define CONST 10;;)
  (some start)
  (;;# $i = 30;;)(local.set $i (i32.const 30))
  (;;# <debug>;;)
  (some code)
  (;;# $i = 10;;)(local.set $i (i32.const 10))
  (;;# </debug>;;)
  (;;# <debug>;;)
  (;;# $i = 11;;)(local.set $i (i32.const 11))
  (;;# </debug>;;)
  (;;# $i = ($k + 11) * 2 + 1;;)(local.set $i (i32.add (i32.mul (i32.add (local.get $k) (i32.const 11)) (i32.const 2)) (i32.const 1)))
  (;;# $i = $m(1 + 2, 10);;)(local.set $i (call $m (i32.add (i32.const 1) (i32.const 2)) (i32.const 10)))
  (;;# [$i] = [10] << $a(CONST) + $m(1 + 2, 10);;)(i32.store (local.get $i) (i32.shl (i32.load (i32.const 10)) (i32.add (call $a (i32.const 10)) (call $m (i32.add (i32.const 1) (i32.const 2)) (i32.const 10)))))
  (;;# $size = [$id];;)(local.set $size (i32.load (local.get $id)))
  (some finish)
  (;;# [SEQ_ID_ADR] = 0;;)(i32.store (i32.const 4) (i32.const 0))
  (;;# $id;;)(local.get $id)
  (;;# $id = $seq_id_next() << 7 + 128 ;; Each set 128 bytes by default;;)(local.set $id (i32.shl (call $seq_id_next) (i32.add (i32.const 7) (i32.const 128))))
  (;;# $i == $size;;)(i32.eq (local.get $i) (local.get $size))
  (;;# 5 != U;;)(i32.ne (i32.const 5) (i32.const 10))
  (;;# $offset = $set_offset_i($id, $size - 1);;)(local.set $offset (call $set_offset_i (local.get $id) (i32.sub (local.get $size) (i32.const 1))))
  (;;# [$offset + 4] = [$offset];;)(i32.store (i32.add (local.get $offset) (i32.const 4)) (i32.load (local.get $offset)))
  (;;# !$size;;)(i32.eqz (local.get $size))
  (;;# $b = $size >> 1;;)(local.set $b (i32.shr_u (local.get $size) (i32.const 1)))
  (;;# $n > get_i($half_index);;)(i32.gt_u (local.get $n) (local.get $half_index))
  (;;# 5 < 1;;)(i32.lt_u (i32.const 5) (i32.const 1))"
`;
